USE SAKILA;
SELECT * FROM FILM;
-- MY FIRST SQL JOURNEY CODE
 USE WORLD;
 SELECT * FROM CITY;
 /* MOST USED STATEMENTS OF SQL 
 SELECT 
 FROM
 WHERE
 GROUP BY
 HAVING
 ORDER BY
 */
SELECT * FROM COUNTRY;
SELECT NAME,POPULATION, GNP,INDEPYEAR 
	FROM COUNTRY
WHERE INDEPYEAR>=1990
ORDER BY GNP DESC;

SELECT REGION,
	COUNT(*) AS TOTAL_COUNTRIES,
    SUM(POPULATION) AS TOTAL_R_POPULATION,
    ROUND(SUM(GNP),0) AS TOTAL_R_GNP,
    ROUND(AVG(LIFEEXPECTANCY),1) AS AVG_R_LE
FROM COUNTRY
GROUP BY REGION
HAVING TOTAL_COUNTRIES>=10
ORDER BY 3 DESC;


 
 
