
DROP DATABASE SALES;

CREATE DATABASE SALES;

SELECT * FROM SALES.RFMDATA;

SELECT COUNT(*) FROM SALES.RFMDATA; -- 2823 RECORDS (ROWS)

SELECT
	ROUND(SUM(SALES), 0) AS TOTAL_SALES
FROM RFMDATA;

-- NUMBER OF CUSTOMERS? -- 92
SELECT
	COUNT(DISTINCT CUSTOMERNAME)
FROM RFMDATA;

-- TOP 10 CUSTOMERS

SELECT
	CUSTOMERNAME,
    COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDER,
	ROUND(SUM(SALES), 0) AS TOTAL_SALES
FROM RFMDATA
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- Customers who made at least 5 orders
SELECT
	CUSTOMERNAME,
    COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDER,
	ROUND(SUM(SALES), 0) AS TOTAL_SALES
FROM RFMDATA
	WHERE PRODUCTLINE = "Motorcycles"
GROUP BY CUSTOMERNAME
HAVING TOTAL_ORDER >= 5
ORDER BY TOTAL_ORDER DESC
;



