-- DDL :DATA DEFINITION LANGUAGED 
CREATE DATABASE SALES;
USE SALES;
DROP DATABASE SALES;
CREATE DATABASE IF NOT EXISTS SALES;
USE SALES;
CREATE TABLE IF NOT EXISTS SALES_DB(
	PURCHASE_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    DATE_OF_PURCHASE DATE,
    ITEM_CODE VARCHAR(10)
 
);

ALTER TABLE SALES_DB
 ADD FOREIGN KEY (CUSTOMER_ID)
		REFERENCES CUSTOMER(CUSTOMER_ID) 
	     ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS ITEM(
    ITEM_CODE VARCHAR(10) NOT NULL PRIMARY KEY,
    UNIT_PRICE NUMERIC(10,2),
    COMPANY_ID VARCHAR(15) NOT NULL
  
);
ALTER TABLE ITEM ADD foreign key(COMPANY_ID)
		references COMPANIES(COMPANY_ID) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS COMPANIES(
    COMPANY_ID varchar(15) NOT NULL PRIMARY KEY,
    COMPANY_NAME CHAR(25),
    HEADQUARTERS VARCHAR(255),
    PHONE_NO VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS CUSTOMER(
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    EMAIL_ADD VARCHAR(255),
    PHONE_NO VARCHAR(20)
   
);
ALTER TABLE CUSTOMER ADD  CUSTOMER_ID INT PRIMARY KEY;
   
    
SELECT * FROM SALES.COMPANIES
