USE EMPLOYEES;
-- EXPLORING EMPLOYEES
SELECT COUNT(*) FROM EMPLOYEES; -- 300024 EMPLOYESS 
SELECT COUNT(EMP_NO) FROM employees;
-- COUNT THE NON NULL NUMBERS
SELECT COUNT(DISTINCT EMP_NO) FROM EMPLOYEES; -- UNIQUE FIELD
SELECT COUNT(DISTINCT FIRST_NAME) FROM EMPLOYEES; -- 1275
SELECT COUNT(DISTINCT LAST_NAME) FROM EMPLOYEES; -- 1637
SELECT MIN(HIRE_DATE) FROM EMPLOYEES; -- FIRST HIRE DATE '1985-01-01'
SELECT MAX(HIRE_DATE) FROM EMPLOYEES; -- LAST  HIRE DATE '2000-01-28'

-- EXPLORING DEPARTMENTS 
SELECT 
    *
FROM
    DEPARTMENTS
ORDER BY DEPT_NO;

-- EXPLORING DEPT_MANAGER

SELECT * FROM DEPT_MANAGER LIMIT 100;

 -- UPDATE
 UPDATE DEPT_MANAGER 
 SET TO_DATE='1999-01-01' WHERE EMP_NO='110039';
UPDATE DEPT_MANAGER 
SET 
    TO_DATE = '1999-01-01'
WHERE
    EMP_NO = '110114';
 -- LEFT JOIN
 SELECT E.FIRST_NAME, DM.DEPT_NO,DM.EMP_NO, DM.FROM_DATE, DM.TO_DATE FROM DEPT_MANAGER AS DM  LEFT JOIN EMPLOYEES AS E ON E.EMP_NO=DM.EMP_NO WHERE DEPT_NO='D001';
 -- TCL( TRANSACTION CONTROL LANGUAGE)
 DELETE FROM DEPT_MANAGER
  WHERE EMP_NO='110039';
  COMMIT;
  ROLLBACK;
-- DELETE AND TRUNCATE   // WHICH ONE IS FASTER? ANS:TRUNCATE
DELETE FROM DEPT_MANAGER;
TRUNCATE DEPT_MANAGER;
DROP TABLE DEPT_MANAGER;

SELECT * FROM TITLES LIMIT 100;
SELECT DISTINCT TITLE FROM TITLES;  -- 7 UNIQUE TITLES
 SELECT * FROM TITLES  WHERE TITLE='MANAGER';
 UPDATE TITLES
 SET TO_DATE='1999-01-01' WHERE TO_DATE='9999-01-01';
-- WILD CARD OPERATOR
SELECT DISTINCT TITLE FROM TITLES WHERE TITLE LIKE ("%ENGINEER%");
SELECT 
    *
FROM
    EMPLOYEES
WHERE
    FIRST_NAME LIKE ('MAR_')
        AND GENDER = 'M';
SELECT 
    *
FROM
    EMPLOYEES
WHERE
    FIRST_NAME LIKE ('%MAR')
        AND GENDER = 'M';
        
SELECT COUNT(*) FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '1980-01-01' AND '1990-12-31';
SELECT 
    COUNT(*)
FROM
    EMPLOYEES
WHERE
    HIRE_DATE >= '1980-01-01'
        AND HIRE_DATE < '1990-12-31';

SELECT * FROM EMPLOYEES WHERE GENDER='M' AND (FIRST_NAME LIKE ('%MAR') OR HIRE_DATE>='1990-01-01'); -- AND IS MORE POWERFUL