-- Q1: LAST YEAR ACTIVE
-- Q2: HOW MANY CUSTOMER FROM LAST YEAR RETAIN IN THIS YEAR AND THEIR CONTRIBUTION ON REVENUE
-- Q3:FIRST TRIP CUSTOMER
-- Q4: HOW MANY FIRST MARCHANT REMAIN IN CURRENT YEAR

-- SOLUTION 
SELECT * FROM cohort_analysis_dataset;

SELECT
	EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEARS, COUNT(customer_id)
 FROM cohort_analysis_dataset
 GROUP BY 1;
 /*
 '2022', '35'
'2023', '34'
'2024', '31' 
*/

-- DUPLICATES
SELECT YEARS,CUSTOMER_ID, RN FROM (SELECT 
    EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEARS,
    customer_id,
    TRANSACTION_DATE,
    REVENUE,
    row_number() OVER (PARTITION BY EXTRACT(YEAR FROM TRANSACTION_DATE), CUSTOMER_ID) AS RN
FROM
    cohort_analysis_dataset)Z
WHERE RN>1 ;
-- WHERE CUSTOMER_ID='Cust_1'


-- LAST YEAR ACTIVE
 
 WITH CTE AS (SELECT 
    EXTRACT(YEAR FROM TRANSACTION_DATE) AS YEARS,
    customer_id,
    TRANSACTION_DATE,
    REVENUE
FROM
    cohort_analysis_dataset),
    
/* -- LAST YEAR ACTIVE

SELECT DISTINCT CUSTOMER_ID AS LAST_YEAR_CUSTOMERS
	FROM CTE
	WHERE YEARS = EXTRACT(YEAR FROM CURRENT_DATE())-1
ORDER BY 1 

-- RETAINED FROM LAST YEAR(active both current and last year


SELECT DISTINCT
    CUSTOMER_ID AS RETAINED_CUSTOMERS
FROM
    CTE
WHERE
    YEARS = EXTRACT(YEAR FROM CURRENT_DATE())
        AND CUSTOMER_ID IN (SELECT DISTINCT
            CUSTOMER_ID AS LAST_YEAR_CUSTOMERS
        FROM
            CTE
        WHERE
            YEARS = EXTRACT(YEAR FROM CURRENT_DATE()) - 1)
ORDER BY 1;
--
SELECT 
    CUSTOMER_ID, MIN(TRANSACTION_DATE) AS FIRST_PARCHASE_DATE, 
    MAX(TRANSACTION_DATE) AS LAST_PARCHASE_DATE
FROM
    CTE
GROUP BY 1;
*/

FIRST_YEAR AS(SELECT 
    CUSTOMER_ID, EXTRACT(YEAR FROM MIN(TRANSACTION_DATE)) AS FIRST_PURCHASE_YEAR 
FROM
    CTE
GROUP BY 1),

FINAL AS( 
SELECT C.*,F.FIRST_PURCHASE_YEAR AS COHORT_YEAR
FROM CTE AS C
LEFT JOIN  FIRST_YEAR AS F
ON C.CUSTOMER_ID=F.CUSTOMER_ID)

/* -- NO NEW CUSTOMER IN 2024 AND VERY FEW IN 2023
SELECT 
    COHORT_YEAR, COUNT(DISTINCT CUSTOMER_ID)
FROM
    FINAL
GROUP BY 1 ; */

SELECT 
    COHORT_YEAR, 
    COUNT( DISTINCT CASE WHEN YEARS=2022 THEN CUSTOMER_ID ELSE NULL END) AS '2022',
    COUNT( DISTINCT CASE WHEN YEARS=2023 THEN CUSTOMER_ID ELSE NULL END) AS '2023',
    COUNT( DISTINCT CASE WHEN YEARS=2022 THEN CUSTOMER_ID ELSE NULL END) AS '2024'
FROM
    FINAL
GROUP BY 1 
